FROM debian:latest
RUN apt-get update
RUN apt-get install -y wget sudo apt-utils

RUN wget -P /tmp http://www.teitok.org/downloads/install-teitok.pl
RUN DEBIAN_FRONTEND="noninteractive" perl /tmp/install-teitok.pl -q

EXPOSE 80 443 22
CMD ["apachectl", "-D", "FOREGROUND"]